-- Esquema inicial: usuarios y préstamos.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE loans (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL,
    amount       NUMERIC(14, 2) NOT NULL,
    term_months  INTEGER        NOT NULL,
    status       VARCHAR(20)    NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    decided_at   TIMESTAMP WITH TIME ZONE,
    decided_by   BIGINT,
    CONSTRAINT fk_loans_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_loans_decided_by FOREIGN KEY (decided_by) REFERENCES users (id),
    CONSTRAINT ck_loans_amount CHECK (amount > 0),
    CONSTRAINT ck_loans_term CHECK (term_months BETWEEN 1 AND 84),
    CONSTRAINT ck_loans_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    -- una solicitud pendiente no tiene decisión; una resuelta la tiene completa
    CONSTRAINT ck_loans_decision CHECK (
        (status = 'PENDING' AND decided_at IS NULL AND decided_by IS NULL)
        OR (status <> 'PENDING' AND decided_at IS NOT NULL AND decided_by IS NOT NULL)
    )
);

CREATE INDEX idx_loans_user_id ON loans (user_id);
CREATE INDEX idx_loans_status ON loans (status);
